# Generated by Django 5.0 on 2023-12-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='form',
            table='Form',
        ),
    ]
