# Generated by Django 5.0 on 2023-12-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0002_alter_form_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
