# Generated by Django 5.0 on 2024-01-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0003_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
